language: php

addons:
  hosts:
    - mysql-container
    - postgres-container
    - dblib-container

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

services:
  - docker

before_install:
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo service pgsql stop || echo "postgres not stopped"
  - npm i @usdocker/usdocker @usdocker/postgres @usdocker/mysql @usdocker/mssql
  - node_modules/.bin/usdocker --refresh
#  - node_modules/.bin/usdocker mssql up
  - node_modules/.bin/usdocker postgres up
  - node_modules/.bin/usdocker mysql up

install:
  - composer install
  - docker ps

script: 
  - vendor/bin/phpunit
#  - vendor/bin/phpunit tests/SqlServerDatabaseTest.php
  - vendor/bin/phpunit tests/PostgresDatabaseTest.php
  - vendor/bin/phpunit tests/MysqlDatabaseTest.php

