name: PHPUnit
on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'byjg/php:${{ matrix.php-version }}-cli'
    strategy:
      matrix:
        php-version:
#          - "8.1"
#          - "8.0"
#          - "7.4"
          - "7.3"
#          - "7.2"
#          - "7.1"
#          - "7.0"
#          - "5.6"

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=20s --health-retries=10

    env:
      MYSQL_TEST_HOST: mysql

    steps:
      - uses: actions/checkout@v2
#      - name: Spin up databases
#        run: |
#          apk add --no-cache python3 python3-dev py3-pip build-base libffi-dev
#          pip3 install --upgrade pip
#          pip3 install docker-compose
#          apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker
#          docker-compose up -d postgres mysql
      - run: composer install
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/phpunit tests/SqliteDatabase*
      - run: ./vendor/bin/phpunit tests/MysqlDatabase*
      - run: ./vendor/bin/phpunit tests/PostgresDatabase*
#      - run: ./wait-for-db.sh mssql && ./vendor/bin/phpunit tests/SqlServer*
